### ISSUE TITLE
The code corresponding to the article

### ISSUE THREAD

**Issue by takerujason** [ChengBinJin/SpineC2M#1]
Dear @ChengBinJin ,

This work is excellent. The review section of this article is instructive.

There is an issue about the directory hierarchy. The directory of code includes `cyclegan`, `mrgan`, `mrganPlus` and `pix2pix`. Which codes respectively correspond to articles "multi-channel GAN", "deep MR-to-CT" and "MR-GAN"?

Looking forward to your answer.
Thank you!

**Comment by ChengBinJin** [comment]
Dear @JCFu 

Thank you for your affirmation. From the implementation aspect, we use the names of the GAN model to simplify their methods. 
- "pix2pix": Multi-channel GAN
- "cyclegan": Deep MR-to-CT
- "mrgan": MR-GAN
- "mrganPlus": MR-GAN+ (it is not included in our paper)

For more detailed information, you can refer to Table 2 of [our paper](https://www.mdpi.com/2076-3417/9/12/2521).

<p align='center'>
  <img src="https://user-images.githubusercontent.com/37034031/64503956-79e8a680-d308-11e9-8e4f-f83e7682337a.png" width=600)
</p>

In addition, the work "DCNN" in the table was also included in our current implementation. You can find this project in the following link:
https://github.com/ChengBinJin/MRI-to-CT-DCNN-TensorFlow

**Comment by takerujason** [comment]
@ChengBinJin 
Thank you so much for the detailed description!
