### ISSUE TITLE
Questions on TFRecord Format and VGG16 CaffeModel

### ISSUE THREAD

**Issue by Phipson** [ChengBinJin/SpineC2M#2]
Dear @ChengBinJin,

Nice to meet you. I am currently a computer science undergraduate student, and as part of a research project me and my research lab is conducting, we are currently performing a comparative analysis on different GAN architectures used to generate synthetic CT images. We came across your paper and would like to reference your work as part of this research. However, when trying to run your code, I ran into some issues that I would like to ask for help and guidance.

1. How is your team formatting your images as TFRecords? I notice that your record features contain both the raw image file and also the image path, but when I try to generate a TFRecord with those inputs, I run into an error due to a formatting issue.

2. How did your team format and produce your VGG16 caffe_layers_value.pickle? We are currently using the caffemodel on model zoo and then generating a pkl file by using a VGG16 prototxt file and the converter from this repository:  https://github.com/pierluigiferrari/caffe_weight_converter. However, the resulting pkl file does not have the correct format for the VGG16 network. 

Thank you for your time, and hope to hear from you soon!

**Comment by ChengBinJin** [comment]
@Phipson 
Hi, I commited a new file named "build_data.py" for converting data to tfrecord format.

Moreover, you can download VGG16 model from the following link 
https://yunpan.360.cn/surl_yxLDnu6QqjQ

**Comment by Phipson** [comment]
Hello @ChengBinJin 
Thank you for your help! I managed to start training thanks to the script and link you provided. Very much appreciated!

**Comment by ChaiqiGUO** [comment]
Hello, the author, I see that the VGG16 model link you shared earlier has expired. Would you please provide it again? This is very important for me, thank you.@ChengBinJin

**Comment by Yangshuo732** [comment]
@Phipson @ChengBinJin  Hello!I don't find the trained VGG16 model weights when I perform the experiment. Could you please send me a copy? [3517162165@qq.com](mailto:3517162165@qq.com) Thank you!
